workflows:
  ios-unsigned:
    name: Build Unsigned iOS (For AltStore)
    instance_type: mac_mini_m2
    environment:
      flutter: default
      xcode: latest
    scripts:
      - name: The Ultimate Xcode Hack 🛠️
        script: |
          set -ex
          flutter pub get
          # 1. اختراق ملفات إعدادات آبل لإلغاء التوقيع بشكل جذري
          echo "CODE_SIGNING_REQUIRED = NO" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGNING_ALLOWED = NO" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGN_IDENTITY = " >> ios/Flutter/Release.xcconfig
          # 2. بناء التطبيق بسلام تام بعد الاختراق
          flutter build ios --release --no-codesign
          # 3. التجهيز والضغط
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr app.ipa Payload
    artifacts:
      - build/ios/iphoneos/app.ipa