workflows:
  ios-unsigned:
    name: Build Unsigned iOS (For AltStore)
    instance_type: mac_mini_m2
    environment:
      flutter: default
      xcode: latest
    scripts:
      - name: Xcode Proper Hack Build 🛠️
        script: |
          set -ex
          flutter pub get
          # 1. بناء نسخة هاتف وهمي لتوليد ملفات الحزم (Podfile)
          flutter build ios --debug --simulator
          # 2. الآن ندخل لمجلد الآيفون ونبني النسخة الحقيقية بدون قيود
          cd ios
          xcodebuild clean build -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -derivedDataPath ../build/ios_derived CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd ../build
          mkdir -p Payload
          find ios_derived/Build/Products -name "*.app" -exec cp -R {} Payload/ \;
          if [ -z "ls -A Payload" ]; then
             echo "ERROR: Payload is empty, build failed."
             exit 1
          fi
          zip -qr app.ipa Payload
    artifacts:
      - build/app.ipa